### ISSUE TITLE
miss disassemble when "push" instruction following by "ret" instruction

### ISSUE THREAD

**Issue by steward-fu** [obsequiousnewt/semblance#4]
Hi zfigura,
Thanks for your great project for PE disassembler.
I noticed that semblance will skip some instructions following by "ret" instruction in _TEXT section as the following:
  401152:	5e                        pop	esi
  401153:	c3                        ret
  401154:	55                        push	ebp
  401155:	8b ec                     mov	ebp, esp

This example code can be obtained from MASM32 examples (MASM32/examples/dialogs/simple/simple.exe).
So far, I did a workaround (return from scan_segment) when next instruction is INT3.

Hope you can fix this issue.
If you need this PE file, please tell me.
Thanks

**Comment by zfigura** [comment]
Thanks for the report. This is actually a "feature"—by default, semblance only dumps code that can be reached through call/jmp instructions. The relevant function that's not dumped is a callback passed by address. You can force semblance to dump everything with -D.

Of course, it's not ideal that it's skipped, but determining what is a function to be disassembled is not always trivial, especially since programs often have text and data interleaved in the same section.

**Comment by steward-fu** [comment]
got it, thanks for your information :)
